package com.michaelfogleman.wordwarrior.protocol.response;

public class ResponseAdapter implements IResponseHandler {
	
	public void handle(AbortResponse response) {}
	public void handle(AcceptResponse response) {}
	public void handle(AdjournResponse response) {}
	public void handle(AdjournedResponse response) {}
	public void handle(AdjudicateResponse response) {}
	public void handle(AdjustResponse response) {}
	public void handle(AliveResponse response) {}
	public void handle(AllObserversResponse response) {}
	public void handle(AsitisResponse response) {}
	public void handle(AskResponse response) {}
	public void handle(AssessResponse response) {}
	public void handle(BestResponse response) {}
	public void handle(BuddiesResponse response) {}
	public void handle(BuddyLoginResponse response) {}
	public void handle(BuddyLogoutResponse response) {}
	public void handle(BuddyStateResponse response) {}
	public void handle(CensorResponse response) {}
	public void handle(ChallengeResponse response) {}
	public void handle(ChangeResponse response) {}
	public void handle(ChannelResponse response) {}
	public void handle(CheckResponse response) {}
	public void handle(ClearResponse response) {}
	public void handle(ClearSeeksResponse response) {}
	public void handle(CloseResponse response) {}
	public void handle(ConnectResponse response) {}
	public void handle(DateResponse response) {}
	public void handle(DeclineResponse response) {}
	public void handle(DeleteResponse response) {}
	public void handle(DisconnectResponse response) {}
	public void handle(DuplicateResponse response) {}
	public void handle(EchoResponse response) {}
	public void handle(ExamineResponse response) {}
	public void handle(FingerResponse response) {}
	public void handle(GamesResponse response) {}
	public void handle(NullResponse response) {}
	public void handle(HelpResponse response) {}
	public void handle(HistoryResponse response) {}
	public void handle(ImportResponse response) {}
	public void handle(KibitzResponse response) {}
	public void handle(LibraryResponse response) {}
	public void handle(ListResponse response) {}
	public void handle(LoginResponse response) {}
	public void handle(MatchResponse response) {}
	public void handle(MessageResponse response) {}
	public void handle(MoreResponse response) {}
	public void handle(MoveResponse response) {}
	public void handle(NoPlayResponse response) {}
	public void handle(NoRelayResponse response) {}
	public void handle(ObserveStartResponse response) {}
	public void handle(ObserveMoveResponse response) {}
	public void handle(ObserveChangeResponse response) {}
	public void handle(ObservePassResponse response) {}
	public void handle(ObserveChallengeResponse response) {}
	public void handle(PasResponse response) {}
	public void handle(PassResponse response) {}
	public void handle(PendingResponse response) {}
	public void handle(PersonalResponse response) {}
	public void handle(PingResponse response) {}
	public void handle(PlayResponse response) {}
	public void handle(PoolResponse response) {}
	public void handle(PreMoveResponse response) {}
	public void handle(RelayResponse response) {}
	public void handle(ReportResponse response) {}
	public void handle(ReserveResponse response) {}
	public void handle(ResignResponse response) {}
	public void handle(ResumeResponse response) {}
	public void handle(SayResponse response) {}
	public void handle(SeekResponse response) {}
	public void handle(SetResponse response) {}
	public void handle(SetAllResponse response) {}
	public void handle(SetFormulaResponse response) {}
	public void handle(SFilterResponse response) {}
	public void handle(ShoutResponse response) {}
	public void handle(SoughtResponse response) {}
	public void handle(ShuffleResponse response) {}
	public void handle(ShutdownResponse response) {}
	public void handle(TellResponse response) {}
	public void handle(UnexamineResponse response) {}
	public void handle(UnmatchResponse response) {}
	public void handle(UnobserveResponse response) {}
	public void handle(UnrelayedResponse response) {}
	public void handle(UnseekResponse response) {}
	public void handle(UptimeResponse response) {}
	public void handle(VarsResponse response) {}
	public void handle(WhisperResponse response) {}
	public void handle(WhoListResponse response) {}
	public void handle(WhoResponse response) {}

}
